### ISSUE TITLE
which JVM versions to support

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.docker#19]
Right now we support the following versions:

```
9.2-jre8
9.3-jre8
9.4-jre8
9.4-jre11
9.4-jre11-slim
9.4-jdk13
9.4-jdk13-slim
```

If we are to support every combination of `JETTY_VERSION`, `JVM_VERSION`, (standard / slim), then the number of versions is going to get quite large with the introduction of jetty-10 & jetty-11 images.

We should decide on exactly which permutations of this we want to include in releases.
I'm also not sure why some of the images use JRE some use JDK, should we provide the option for either for any particular Java versions?

**Comment by gregw** [comment]
Some of the issues are dictated by availability eg there are no JRE images available for java-13.

For EOL releases 9.2 and 9.3, I think just releasing the single jre8 image is correct.
More over 9.4 will exist into the future because of it's java-8 support, so it definitely need that.
In fact, we could probably flip this around the other way and say what jetty releases are available for jre8.  The answer is 9.2, 9.3 and 9.4

The question is, what java releases should be supported for live release: 9.4, 10 & 11.
We can see the list of options include jre11, jre11-slim, jdk13, jdk13-slim.     Are there any other options?
There is a reason to keep java8 support, but I'm not sure if there is a reason to keep java11 support long term?  @sbordet @joakime what is the official status of java11 into the future?

For now, I think it costs us little to have a full support matrix, so let's add most option combinations for 9.4, 10 & 11... but we need to come up with a policy of when to drop them... and that may well be we drop them when the base images needed are dropped?





Then the question is, which

**Comment by lachlan-roberts** [comment]
So maybe we should keep the current support matrix but update the JDK13 to use JDK14 instead?
Then the complete list would look something like this:
```
9.2-jre8
9.3-jre8
9.4-jre8
9.4-jre11
9.4-jre11-slim
9.4-jdk14
9.4-jdk14-slim
10.0-jre11
10.0-jre11-slim
10.0-jdk14
10.0-jdk14-slim
11.0-jre11
11.0-jre11-slim
11.0-jdk14
11.0-jdk14-slim
```

**Comment by olamy** [comment]
+1 to drop 13 and replace with 14.

**Comment by lachlan-roberts** [comment]
The images added in #23 included both JDK and JRE version where possible.
The final list of supported versions is now:
```
9.2-jre8
9.3-jre8
9.4-jre8
9.4-jdk8
9.4-jre11
9.4-jdk11
9.4-jdk14
9.4-jre8-slim
9.4-jdk8-slim
9.4-jre11-slim
9.4-jdk11-slim
9.4-jdk14-slim
10.0-jre11
10.0-jdk11
10.0-jdk14
10.0-jre11-slim
10.0-jdk11-slim
10.0-jdk14-slim
11.0-jre11
11.0-jdk11
11.0-jdk14
11.0-jre11-slim
11.0-jdk11-slim
11.0-jdk14-slim
```
